### ISSUE TITLE
[Question] Is VGM logging support in plans?

### ISSUE THREAD

**Issue by sunkhaskasis** [nukeykt/Nuked-MD#30]
I know that it's probably way too early to ask for such a feature, considering that the emulator is still heavily WIP, but I'm wondering if having VGM logging is considered once more progress is made. While BlastEm does a pretty good job at VGM logging right now, IMO it never hurts to implement the feature in a more accurate emulator.

**Comment by superctr** [comment]
It would take many hours (maybe even days) to just log a single song, so I'm not sure if it would be very practical.

**Comment by ogamespec** [comment]
I'll answer for @nukeykt, he's too loyal.
VGM support is NOT specifically planned by us.
The emulator is not "heavily WIP". It is fully ready - all chips are simulated properly.
The only thing I would like to see for the Mega Drive soft core is support for save-states, and also a visual debugger on imgui so you can hack games. And preferably a good wizard would do it all instead of us.
